### ISSUE TITLE
Code style settings Intellij IDEA

### ISSUE THREAD

**Issue by AndyWynham** [l3r8yJ/screener-api#60]
Folow guide in the master branch ([CODESTYLE_GUIDE.md](https://github.com/l3r8yJ/screener-api/blob/master/CODESTYLE_GUIDE.md)) and write when you're done

**Comment by AndyWynham** [comment]
Done

**Comment by SergeyShapovaIov** [comment]
Done

**Comment by desmeach** [comment]
Done

**Comment by NikiTuz18** [comment]
Plagin is installed, but I don't understand about which "Checkstyle.xml " the file says in the guide, *bruh* D:

**Comment by l3r8yJ** [comment]
@NikiTuz18 [this](https://github.com/l3r8yJ/screener-api/blob/master/Checkstyle.xml) file

**Comment by NikiTuz18** [comment]
Done
![image](https://user-images.githubusercontent.com/104133517/189821529-7ef24cc6-7e45-4fd4-97f9-d2d06ec1f74d.png)
